### ISSUE TITLE
Would love to see a portable version...

### ISSUE THREAD

**Issue by DaSandman** [drweb86/butil#173]
I'd love to see a portable version of BUtil available,, if possible.

**Comment by drweb86** [comment]
Hi. Can you please describe your usage scenario for portable version?
Is it because of Windows SmartScreen?

**Comment by DaSandman** [comment]
It would enable it's use on a thumbdrive, or portable SSD, or of course on a local drive without necessarily writing to the registry.

**Comment by drweb86** [comment]
Hi @DaSandman 

I've added deployment as 7z archive. Please reopen if does not meet your portable expectations.
