### ISSUE TITLE
BUtil 2023.09.21 - GUI issues

### ISSUE THREAD

**Issue by bovirus** [drweb86/butil#190]
@drweb

Pelase check screenshots.

The "Esegui (=Run)" button seems not aligned vertically with the relative box.

![image](https://github.com/drweb86/butil/assets/1262554/ee8e6cbb-2079-4e8b-b25e-c5dd188633c0)

![image](https://github.com/drweb86/butil/assets/1262554/9c0a0db9-3fdf-4e4a-b226-d9f8c8dbcec5)

Note;: this very long string without CR/LF it's very hard to read

![image](https://github.com/drweb86/butil/assets/1262554/903bbc91-e9a7-4de4-8112-21885fb29624)

I prpose youi to modify teh string to add a CR/LKF for each paragraph.

**Comment by drweb86** [comment]
Thanks. I changed mentioned buttons to icons and added separators. As for me it did not become better. Probably remove that text at all since everyone has google nowadays.

**Comment by bovirus** [comment]
@drweb86 

The new button has no aligned and has no ballon help then for me is not clear the scope.
Or enable ballon help for these or go back to button interface

![image](https://github.com/drweb86/butil/assets/1262554/b336e4bf-105e-4e71-9949-1b3dca00f061)

The caption is not "New task - task". For em should be "New task".
Then you have two kind of caption

"New task"
"New multimedis task"

**Comment by drweb86** [comment]
Wov. I switched to 150% DPI and did not realized they won't work at 100% dpi

**Comment by bovirus** [comment]
For me main window caption should be

"BUtil yyyy.mm.ddd" 

and not like now 

"Task yyyy.mm.dd"

![image](https://github.com/drweb86/butil/assets/1262554/a53dbc42-1410-4891-9ff3-3cd3fca2249c)

**Comment by drweb86** [comment]
Will be fixed in new release.
