### ISSUE TITLE
Ошибка отображения цели действия

### ISSUE THREAD

**Issue by Kopejkin** [drweb86/butil#319]
Incremental backup task -> Источник : C:\1111;  Цель: D:\2222
лог в окне выполнения:
Get state of **source** item "C:\1111"
Здесь все правильно.
=================
Import media task -> Источник : C:\1111;  Цель: D\2222
лог в окне выполнения:
Get state of **source** item "D:\2222"
Так должно быть?
=================
P.S. **source** выделено мною, чтобы понятнее было, о чем речь.

**Comment by drweb86** [comment]
Слово source лишнее. Но получать состояние оно должно, чтобы пропускать копирование уже существующих файлов.

**Comment by Kopejkin** [comment]
Я писал о том, что в первом случае отображается путь к папке ИСТОЧНИКА,
затем проверяется папка ЦЕЛИ.
А во втором случае (где медиа) отображается путь к папке ЦЕЛИ и проверяется
папка ЦЕЛИ.

Кстати, если очистить целевую папку, а затем запустить задание не отключая
опцию копирования уже имеющихся файлов, программа рапортует об успешном
завершении задания. А резервные файлы-то тю-тю! То есть программа по факту
ничего не проверяет в целевой папке.

А еще хотелка есть - добавьте маленькую кнопочку выбора языка. Если моя
система не поддерживает ни один из имеющихся в наличии языков, зачем мне
все эти файлы на диске?

С уважением, Вадим.

чт, 13 черв. 2024 р. о 22:46 Siarhei Kuchuk ***@***.***> пише:

**Comment by drweb86** [comment]
> Кстати, если очистить целевую папку, а затем запустить задание не отключая
опцию копирования уже имеющихся файлов, программа рапортует об успешном
завершении задания. А резервные файлы-то тю-тю! То есть программа по факту
ничего не проверяет в целевой папке.
Импорт мультимедиа не предназначен для резервного копирования. Он предназначен для импорта мультимедиа. Флажок Пропускать ранее скопированные файлы так и задумывался. После импорта фотографий с фотоаппарата пользователь удаляет весь шлак - что 90% фоток, и чтобы при повторном импорте - эти же файлы назад не появились.

**Comment by Kopejkin** [comment]
Здравствуйте, Сергей.
Если посчитаете возможным добавить украинский язык, ниже представлена
ссылка на готовую языковую библиотеку BUtil.Core.resources.dll и CSV-файл
BUtil.Core.resources-EN-UK.csv в формате ID-EN-UK, так как Gmail не
разрешает отправку исполняемых файлов.

BUtil-Ukrainian-Language.zip     15.5 KB
https://drive.google.com/file/d/1oNWzwuseXKlLkRL-nLdzBLx2oZaHXTNS/view?usp=sharing
SHA1: 3FE5FB2EC397575616BCCB4CBCE7720F1D97DBC0

С уважением, Вадим.

сб, 15 черв. 2024 р. о 15:07 Siarhei Kuchuk ***@***.***> пише:

**Comment by drweb86** [comment]
Здравствуйте,

Спасибо. Добавил в приложение. Вместе с новой версией будет украинский язык. Новую версию я думаю после этих или новых выходных выпустить, когда закончу с добавлением синхронизации.

**Comment by drweb86** [comment]
@Kopejkin , https://github.com/drweb86/butil/releases/tag/2024.06.29
